on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: package.json          

      - name: 🚚 Get latest code
        uses: actions/checkout@v2.5.0

      - name: Clean install dependencies
        run: npm ci

      - name: Build app
        run: npm run build.full

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
